export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const FETCH_ALL = 'FETCH_ALL'
export const DELETE = 'DELETE'
export const LIKE = 'LIKE'
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const ERROR = 'ERROR'

